project:
  type: website
  
  output-dir: docs
lang: fr


website:
  title: ""
  cookie-consent:
   style: simple
   type: express

  # comments: 
  #  utterances:
  #    repo: oousmane/cdc-website
  #    label: Commentaires
  repo-url: https://github.com/oousmane/quarto-blog
  open-graph: true
  twitter-card:
    creator: "@oousmane_11"
    card-style: summary_large_image
  navbar:
#    background: "#2c2c2c"
#   logo: logo_name.png
    left:
      - text: Ousmane Ouedraogo
        href: index.qmd
      
    right:
      - text: Blog
        href: blog.qmd
      - text: Formations 
        href: formations.qmd
      - text: Projets
        href: Projets.qmd
      #- text: Talks
       # href: 404.qmd
      - text: CV
        href: CV.qmd
      #- contact.qmd
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/oousmane_11
      - icon: github
        aria-label: github
        href: https://github.com/oousmane
      - icon: facebook
        aria-label: facebook
        href: https://www.facebook.com/oousmane.aly
     
  page-footer: 

   left: |
    Réalisé avec 
    [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)
   right: |
    [{{< fa brands github >}} ](https://github.com/oousmane/quarto-blog/)
   center: |
    [Licence](Licence.qmd)

lightbox: auto

format:
  html:
    theme:
      light: [cosmo, styles/custom.scss, styles/custom-light.scss]
      dark: [darkly, styles/custom.scss, styles/custom-dark.scss]
execute: 
  freeze: true
editor: visual
