project:
  type: website
  
  output-dir: docs
lang: fr


website:
  title: ""
  cookie-consent:
   style: simple
   type: express

  # comments: 
  #  utterances:
  #    repo: oousmane/cdc-website
  #    label: Commentaires
  repo-url: https://github.com/oousmane/quarto-blog
  open-graph: true
  twitter-card:
    creator: "@oousmane_11"
    card-style: summary_large_image
  navbar:
    background: "#eeeeee"
    logo: logo_name.png
    
    right:
      - text: Accueil
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: Formations 
        href: formations.qmd
      #- text: Talks
       # href: 404.qmd
      - text: CV
        href: resume/resume.pdf
      #- contact.qmd
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/oousmane_11
      - icon: github
        aria-label: github
        href: https://github.com/oousmane
      - icon: facebook
        aria-label: facebook
        href: https://www.facebook.com/oousmane.aly
     
  page-footer: 
   left: |
  
    All content are © Ousmane Ouedraogo and licensed under
    [Creative Commons](https://creativecommons.org/licenses/by-sa/4.0/)
   right: |
    [{{< fa brands github >}} ](https://github.com/oousmane/quarto-blog)
    
format:
  html:
    theme: ember.scss
    css: styles.css
execute: 
  freeze: true
editor: visual
