project:
  type: website
  
  output-dir: docs
lang: fr


website:
  title: ""
  cookie-consent:
   style: simple
   type: express

  # comments: 
  #  utterances:
  #    repo: oousmane/cdc-website
  #    label: Commentaires
  repo-url: https://github.com/oousmane/quarto-blog
  open-graph: true
  twitter-card:
    creator: "@oousmane_11"
    card-style: summary_large_image
  navbar:
    background: "#eeeeee"
    logo: logo-circle.jpg
    left:
      - text: Blog
        href: blog.qmd
      - text: CV
        href: resume/resume.pdf
    right: 
      - contact.qmd
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/oousmane_11
      - icon: github
        aria-label: github
        href: https://github.com/oousmane
      - icon: facebook
        aria-label: facebook
        href: https://www.facebook.com/oousmane.aly
     
  page-footer: 
   left: |
  
    All content licensed under a {{< fa brands creative-commons >}}
    {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
    [(CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/)
   right: |
    [{{< fa brands github >}} ](https://github.com/oousmane/quarto-blog)
    
format:
  html:
    theme: ember.scss
    css: styles.css
execute: 
  freeze: true
editor: visual
