---
layout: page
title: "Ousmane Ouedraogo"
subtitle: Météorologiste, TS
editor: visual
---

```{=html}
<div align="center">
<a href="mailto:jasmine.dumas@gmail.com" class="btn btn-success"><span class="glyphicons glyphicons-envelope"></span>Email</a>
<a href="https://jasdumas.github.io/" class="btn btn-success"><span class="glyphicons glyphicons-pencil"></span>Website & Blog</a>
<a href="https://jasdumas.github.io/jasmine_daly_resume_updated_december_2019.pdf" class="btn btn-success"><span class="glyphicons glyphicons-download-alt"></span>Download CV PDF</a>  
</div>
```
### About Me

Salut 👋🏻 je suis météo 🌦️ et je travaille à l\'**Agence Nationale de la Météorologie** à **Ouagadougou, Burkina Faso**.
Je suis particulièrement passionné d\'analyse et visualisation de données, de climat et de machine learning.
Aussi j\'adore apprendre et partager de nouvelle choses au quotidien.

-   Forecasting edge cloud computing metrics for a global CDN
-   Optimizing the onboarding experience for an online bank through experimentation
-   Developing machine learning models to predict auto insurance premiums
-   Conducting mechanical testing of medical devices for FDA approval
-   Leveraging computer-aided design to illustrate jet engine components

### Education

-   **Graduate Analytics Certificate** at [DePaul University](https://www.cdm.depaul.edu/academics/Pages/Current/Analytics-Certificate.aspx), (2015 - 2017)
    -   *Coursework*: Intro to Programming, Data Analytics & Regression, Database Processing for Large-scale Analytics, Advanced Data Analysis, Knowledge Discovery Technologies, Programming Machine Learning Applications
-   **BS in Engineering in Biomedical Engineering** at [University of Hartford](http://www.hartford.edu/ceta/undergraduate/engineering/BM/), (2008 - 2012)
    -   *Coursework*: Engineering Computer Applications, Calculus (1-2, Multivariable), Differential Equations, Independent Research, Engineering Design, Statics, Dynamics, Mechcanics of Materials, Biomaterials
